# Generated by Django 5.1.6 on 2025-03-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprompt',
            name='created_at',
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageprompt',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
