# Generated by Django 5.1.7 on 2025-04-10 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_remove_imageprompt_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
