# Generated by Django 5.2.1 on 2025-06-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_imageprompt_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprompt',
            name='description',
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='imageprompt',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
