# Generated by Django 5.2.1 on 2025-06-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_remove_imageprompt_description_imageprompt_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprompt',
            name='video',
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='video_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='imageprompt',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
