# Generated by Django 5.2.1 on 2025-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0005_remove_imageprompt_video_imageprompt_video_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprompt',
            name='video_path',
            field=models.FilePathField(blank=True, null=True, path='media/videos'),
        ),
    ]
