# Generated by Django 5.0.1 on 2025-06-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0006_alter_imageprompt_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprompt',
            name='video_path',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
